"""Regenerate independent golden packets with pymavlink's generated dialect."""
from pathlib import Path
from pymavlink.dialects.v20 import common as mav

root = Path(__file__).resolve().parents[1]
ap = mav.MAVLink(None, srcSystem=17, srcComponent=1)
gcs = mav.MAVLink(None, srcSystem=254, srcComponent=190)
packets = {}
for name, message in [
    ('ping', mav.MAVLink_ping_message(0, 0, 0, 0)),
    ('read', mav.MAVLink_param_request_read_message(17, 1, b'', 300)),
    ('set', mav.MAVLink_param_set_message(17, 1, b'TEST_PARAM', 1.25, 9)),
    ('read_name', mav.MAVLink_param_request_read_message(17, 1, b'BATT_MONITOR', -1)),
]:
    packets[name] = message.pack(gcs, force_mavlink1=True).hex()
    gcs.seq += 1
for name, message in [
    ('heartbeat', mav.MAVLink_heartbeat_message(1, 3, 1, 0, 3, 3)),
    ('value', mav.MAVLink_param_value_message(b'TEST_PARAM', 1.25, 9, 301, 300)),
    ('value_name', mav.MAVLink_param_value_message(b'BATT_MONITOR', 1.25, 9, 301, 65535)),
    ('truncated', mav.MAVLink_heartbeat_message(1, 3, 0, 0, 0, 0)),
]:
    packets[name] = message.pack(ap).hex()
    if name != 'truncated':
        packets[name + '1'] = message.pack(ap, force_mavlink1=True).hex()
    ap.seq += 1
target = root / 'tests' / 'fixtures' / 'mavlink.lua'
target.parent.mkdir(exist_ok=True)
target.write_text('-- Generated by tools/mav_vectors.py using pymavlink v20/common.\nreturn {\n' +
                  ''.join(f"  {name}='{packet}',\n" for name, packet in packets.items()) + '}\n',
                  newline='\n')
print(target)
